### ISSUE TITLE
Add yaml support

### ISSUE THREAD

**Issue by booyaa** [booyaa/wizardbanner#2]
example for `ee.yml`
```yml
- url: http://add-on.ee.co.uk/status
- type: html
- path: //p[@class='status-pass-summary']
- regexp: ([0-9]+)([KGM]B)
- return: first
```

type: xml, html, json
path: xpath, json dot notation
regexp: go regex syntax
return: return `first` or `all` results from regexp
